services:
  - type: web
    name: kermhosting
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true